# -*- coding: utf-8 -*-
"""running_sum_array1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwBL2Xtr0pfJvi9WPXDkRO5kPwmdql2V
"""

from typing import List

class Solution:
    def runningSum(self, nums: List[int]) -> List[int]:
        running_sum = []
        current_sum = 0
        for num in nums:
            current_sum += num
            running_sum.append(current_sum)
        return running_sum