# -*- coding: utf-8 -*-
"""shuffle the array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ph2ySgcDUnqcr-o7NcglsMvwkuhCXUCN
"""

from typing import List

class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        result = []
        for i in range(n):
            result.append(nums[i])      # xi
            result.append(nums[i + n])  # yi
        return result